# Generated by Django 2.2.7 on 2019-11-18 17:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Peluquero',
            fields=[
                ('DNI', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=50)),
                ('trabajaMujer', models.BooleanField(default=True)),
                ('trabajaHombre', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('genero', models.CharField(choices=[(1, 'Hombre'), (2, 'Mujer')], default=2, max_length=7)),
                ('nombre', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('precio', models.IntegerField(default=10)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('email', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('apellidos', models.CharField(max_length=60)),
                ('imagen', models.ImageField(null=True, upload_to='fotos/')),
                ('genero', models.CharField(choices=[(1, 'Hombre'), (2, 'Mujer')], default=2, max_length=7)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
