# Generated by Django 2.2.7 on 2019-11-20 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pelu', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='email',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='imagen',
        ),
        migrations.AddField(
            model_name='cliente',
            name='auto_increment_id',
            field=models.AutoField(default='1', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='peluquero',
            name='DNI',
            field=models.CharField(default='11111587d', max_length=9, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='nombre',
            field=models.CharField(default='pelado', max_length=20, primary_key=True, serialize=False),
        ),
    ]
