# Generated by Django 2.2.7 on 2019-11-20 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pelu', '0003_remove_cliente_genero'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='auto_increment_id',
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nombre',
            field=models.CharField(default='rafa', max_length=20, primary_key=True, serialize=False),
        ),
    ]
