# Generated by Django 2.2.7 on 2019-11-20 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pelu', '0005_cliente_genero'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='imagen',
            field=models.ImageField(null=True, upload_to='fotos/'),
        ),
    ]
