# Generated by Django 2.2.7 on 2019-11-20 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pelu', '0006_cliente_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='genero',
            field=models.CharField(choices=[('Hombre', 'Hombre'), ('Mujer', 'Mujer')], default=2, max_length=7),
        ),
    ]
