# Generated by Django 2.2.7 on 2019-11-21 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pelu', '0008_auto_20191121_1719'),
    ]

    operations = [
        migrations.AddField(
            model_name='peluquero',
            name='imagen',
            field=models.ImageField(null=True, upload_to='fotos/'),
        ),
    ]
