# Generated by Django 2.2.7 on 2019-11-25 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pelu', '0012_trabajo_hora'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabajo',
            name='hora_js',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
